version: "3.8"

services:
  insight-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
      - TESSERACT_CMD=/usr/bin/tesseract
      - PORT=8000
      - GEMINI_MODEL=gemini-2.5-flash
      - MAX_FILE_SIZE_MB=50
      - IMAGE_QUALITY=2
      - MAX_IMAGE_SIZE=4096
    volumes:
      - ./uploads:/app/uploads
      - ./app/models:/app/app/models
    env_file:
      - .env
    restart: unless-stopped

volumes:
  uploads:
