services:
  - type: web
    name: insight-api
    env: docker
    dockerfilePath: ./Dockerfile
    repo: # Add your GitHub repo URL here
    branch: main # or master
    dockerContext: .
    envVars:
      - key: GOOGLE_AI_API_KEY
        sync: false # Set this in Render dashboard
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
      - key: PORT
        value: 10000
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: MAX_FILE_SIZE_MB
        value: 50
      - key: IMAGE_QUALITY
        value: 2
      - key: MAX_IMAGE_SIZE
        value: 1920
      - key: PYTHONPATH
        value: /app
    disk:
      name: insight-disk
      mountPath: /app/uploads
      sizeGB: 1
    healthCheckPath: /health
    plan: starter # Change to 'standard' or higher for production 