services:
  - type: web
    name: form-analyzer-api
    env: docker
    region: frankfurt  # أقرب منطقة للشرق الأوسط
    plan: free
    healthCheckPath: /docs
    dockerCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: AZURE_OPENAI_API_KEY
        sync: false  # سيتم إضافتها يدوياً في لوحة التحكم
      - key: AZURE_OPENAI_ENDPOINT
        sync: false
      - key: AZURE_OPENAI_API_VERSION
        value: 2024-02-15-preview
      - key: AZURE_OPENAI_DEPLOYMENT_NAME
        value: gpt-4.1
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: ELEVENLABS_ENGLISH_VOICE_ID
        value: 1SM7GgM6IMuvQlz2BwM3
      - key: ELEVENLABS_ARABIC_VOICE_ID
        value: 1qEiC6qsybMkmnNdVMbK 